### PR TITLE
Fix a compilation error

### PR DESCRIPTION
**Pull request by nunobaldaia**
Hi, this is a minor change that just fixes a compilation error.

### CODE REVIEW

**Comment by groue** [comment]
Hi @nunobaldaia. Hasn't it already been fixed by #92?

**Comment by nunobaldaia** [comment]
Hi @groue.

Yes, you are right, #92 fixed that issue. I haven't noticed that pull request. However, that line is not present on the current master branch: https://github.com/groue/GRMustache/blob/master/src/classes/Compiling/TemplateAST/GRMustacheTag.h

Neither on v7.3.1.

**Comment by groue** [comment]
Oh, it looks like I messed up the last PR.

**Comment by nunobaldaia** [comment]
Thanks! :)

**Comment by groue** [comment]
I'll release 7.3.2 with the actual include of this change... Hold on a minute :-)

**Comment by groue** [comment]
v7.3.2 has shipped with your fix: https://github.com/groue/GRMustache/blob/master/src/classes/Compiling/TemplateAST/GRMustacheTag.h

Thanks @nunobaldaia!

**Comment by nunobaldaia** [comment]
Thanks Gwendal!

**Pull request merged**
