### PR TITLE
GRMustache 8.0.0 need to be released!

### PR DESCRIPTION
**Pull request by haifengkao**

### CODE REVIEW

**Comment by groue** [comment]
What does this PR do?

**Comment by haifengkao** [comment]
I need a way to use GRMustache 8.0.0.
What I did:
1. update the version number to 8.0.0
2. update the source file location, otherwise cocoapods won't include any files in GRMustache

Now I can install it by 
`pod 'GRMustache', :git => 'https://github.com/haifengkao/GRMustache.git', :branch => 'patch-2'`

If you could officially release it, it would be easier for us to use.

**Comment by groue** [comment]
OK. Keep on using your fork until the work is complete. But some stuff is still missing for a proper release. Thank you for reminding me of this.

**Comment by haifengkao** [comment]
It has been a month. Any news?

**Pull request closed without merging**
